### ISSUE TITLE
Unable to start BTtons on latest Sailfish OS

### ISSUE THREAD

**Issue by jsarkari01** [jgibbon/harbour-btbuttons#3]
Hello,  I am unable to start this app on.my Sony Xperia 10 Plus Dual SIM since updating.to Sailfish OS 4.0.1.48.  I have tried removing paired car device and un installing this app.and re installing but that doesn't work.

**Comment by jgibbon** [comment]
Hi! Ideally, you shouldn't need to start it on 4.0.1 – Jolla has finally built the functionality into sfos itself.

cheers!
