### ISSUE TITLE
aarch64 build?

### ISSUE THREAD

**Issue by poetaster** [jgibbon/harbour-btbuttons#4]
The updates this year make it impossible to install on newer (> 4.x) versions of SFOS since only 64bit support is available. Have you thought about putting the package on chum, the automated obs build system from jolla, with sauce?

**Comment by jgibbon** [comment]
The functionality should be included in SFOS >=4 – so I haven't really thought about that, at least for this application. 

What would be your use case for "BTtons" on recent SFOS releases?

cheers

**Comment by poetaster** [comment]
It was my itchy trigger finger. Started with mpris debugging: https://forum.sailfishos.org/t/4-3-0-mpris-proxy-not-active-by-default
I maintain a list of missing packages  at https://forum.sailfishos.org/t/apps-that-havent-been-ported-to-aarch64/
I'll remove Btbuttons since it seems I jumped the gun.

**Comment by jgibbon** [comment]
OK, no problem. I'll close this issue then. :)

cheers!
